[package]
name = "scl-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
rand = "0.8.5"
log = "0.4.22"
rustls = "0.23.16"
serde_json = "1.0.132"
bincode = "1.3.3"
serde = { version = "1.0.214", features = ["derive"] }
env_logger = "0.11.5"
