[package]
name = "scl-rs"
version = "0.1.0"
edition = "2021"
author = "hdvanegasm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "2.0.12"
rand = "0.9.1"
log = "0.4.22"
rustls = "0.23.26"
serde_json = "1.0.132"
bincode = { version = "2.0.1", features = ["serde"] }
serde = { version = "1.0.214", features = ["derive"] }
env_logger = "0.11.5"
crypto-bigint = { version = "0.6.1", features = ["serde"] }
